Document: pomeranian
Title: Debian pomeranian Manual
Author: <insert document author here>
Abstract: This manual describes what pomeranian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pomeranian/pomeranian.sgml.gz

Format: postscript
Files: /usr/share/doc/pomeranian/pomeranian.ps.gz

Format: text
Files: /usr/share/doc/pomeranian/pomeranian.text.gz

Format: HTML
Index: /usr/share/doc/pomeranian/html/index.html
Files: /usr/share/doc/pomeranian/html/*.html
